---
- ansible.builtin.assert:
    that:
      - src is defined
      - dest is defined
    quiet: true
    fail_msg: 'Missing required parameters'

- name: Ensure rsync is installed
  ansible.builtin.dnf:
    name: rsync
    use_backend: dnf4
  become: yes

- name: "rsync {{ src }} to {{ dest }}"
  ansible.posix.synchronize:
    src: "{{ src }}"
    dest: "{{ dest }}"
