---
name: Release collection
on:
  workflow_dispatch:

jobs:
  release:
    uses: ansible-middleware/github-actions/.github/workflows/release.yml@main
    secrets: inherit
    with:
      collection_fqcn: 'community.fqcn_migration'
      galaxy_token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
